// Qualification
export const ADD_QUALIFICATION = 'ADD_QUALIFICATION'
export const ADD_UNIT_TO_QUALIFICATION = 'ADD_UNIT_TO_QUALIFICATION'
export const SET_QUALIFICATION_STATE = 'SET_QUALIFICATION_STATE'
export const QUALIFICATION_SAVED = 'QUALIFICATION_SAVED'
export const UPDATE_QUALIFICATION_TITLE = 'UPDATE_QUALIFICATION_TITLE'
// Units
export const ADD_UNIT_TO_GROUP = 'ADD_UNIT_TO_GROUP'
export const REMOVE_UNIT_FROM_GROUP = 'REMOVE_UNIT_FROM_GROUP'
export const SEARCH_UNITS = 'SEARCH_UNITS'
// Groups
export const ADD_NEW_GROUP = 'ADD_NEW_GROUP'
export const SPLIT_FROM_CRITERIA = 'SPLIT_FROM_CRITERIA'
export const MERGE_GROUP = 'MERGE_GROUP'
export const DELETE_GROUP = 'DELETE_GROUP'
export const UPDATE_MIN_SCORE = 'UPDATE_MIN_SCORE'
export const UPDATE_GROUP_TITLE = 'UPDATE_GROUP_TITLE'

//Criteria
export const CHANGE_SCORE_CRITERIA = 'CHANGE_SCORE_CRITERIA'
export const SET_CRITERIA_TYPE = 'SET_CRITERIA_TYPE'

